# Generated by Django 5.1 on 2024-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pic.jpg', null=True, upload_to='')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='users_stude_id_b41c0e_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Routing',
        ),
    ]
