# Generated by Django 5.1 on 2024-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_pic_student_delete_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enroll',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=50, null=True)),
                ('field1', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-student'],
                'indexes': [models.Index(fields=['-student'], name='users_finge_student_d380a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sign_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-student'],
                'indexes': [models.Index(fields=['-student'], name='users_sign__student_6bdf25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sign_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-student'],
                'indexes': [models.Index(fields=['-student'], name='users_sign__student_dc44e6_idx')],
            },
        ),
    ]
