# Generated by Django 5.1 on 2024-09-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_enroll_fingerprint_sign_in_sign_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerprint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sign_in',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sign_out',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='users_finge_student_d380a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='sign_in',
            name='users_sign__student_6bdf25_idx',
        ),
        migrations.RemoveIndex(
            model_name='sign_out',
            name='users_sign__student_dc44e6_idx',
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['-created_at'], name='users_finge_created_a28baa_idx'),
        ),
        migrations.AddIndex(
            model_name='sign_in',
            index=models.Index(fields=['-created_at'], name='users_sign__created_22585c_idx'),
        ),
        migrations.AddIndex(
            model_name='sign_out',
            index=models.Index(fields=['-created_at'], name='users_sign__created_22f381_idx'),
        ),
    ]
